### ISSUE TITLE
remove/redo environement.yaml.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/scipy2018-jupyterLab-tutorial#3]
The environement.yaml seem to lead to a lot of trouble with versions incompatible with systems. I think that only the minimal list of packages w/o pinned version numbers is better. 

@jasongrout, you were the one pushing to have a frozen version with hashes, could you judge on this ?

**Comment by willingc** [comment]
Probably would be better to do as @Carreau recommends or allow the versions to float upward. I wouldn't pin the dependencies of dependencies ;-)

**Comment by Carreau** [comment]
I just did it and pushed a minimal env.yaml with nothing pinned. It's not only a question of minimal version it's also it was pinning things that were os-specific like appnope.

**Comment by Carreau** [comment]
The size of the environment.yaml is unreasonable. I just tried in a fresh docker container to bootstrap this, and it's been runing for close to 10 minutes just downloading. 

The original reason I was against environment.yaml at the beginning was exactly this reason. I have powerful machine, and a good network and bootstraping the  tutorial is killing it ... We need to slim down the env more.

**Comment by jasongrout** [comment]
I think the environment.yaml that was merged is too heavy. I think it also should use conda forge packages.

**Comment by jasongrout** [comment]
If we can pin across os, I like the idea of pinning all versions. However, like you say, that probably isn't practical across different operating systems

**Comment by jasongrout** [comment]
> @jasongrout, you were the one pushing to have a frozen version with hashes, could you judge on this ?

Just to clarify, I was suggesting a few weeks ago that we should take the instructions from the readme, create the environment using them, then create an environment.yml from that.  You bring up good points that even this may not be cross-platform.

It looks like what was actually done was to maybe try to mirror the demo repo (which has a much heavier environment), so maybe there was some miscommunication about the intent of using an environment.yml. I didn't review the actual PR before someone merged it.

At this point, I would be in favor of removing the environment.yml and reverting back to our original install instructions that pinned a few top-level packages (like pandas). I'll put in a PR for doing that.

**Comment by jasongrout** [comment]
> I didn't review the actual PR before someone merged it.

Ah, it looks like the commits were pushed directly to master, since we were just all working on the repo. I should have looked at those commits before they were pushed to master (or even after to catch the difference).

**Comment by jasongrout** [comment]
Actually, it looks like I was wrong, sorry! I didn't realize, for example, that dask was pulled in by scikit-image, which was pulled in by ipyvolume. So perhaps the environment.yml file that was created *was* from the instructions we provided, rather than the demo.

Still, I do like your trimmed down environment.yml without the version numbers.

**Comment by jasongrout** [comment]
I just pushed a commit switching the instructions back to creating the environment from the command line, with a parenthetical comment that you could instead use the environment.yml. I also simplified the environment.yml down to just what was needed, to match the command line. Since we removed the version numbers, there is little reason for the environment.yml to contain all packages.

**Comment by Carreau** [comment]
Thanks. I think it would be a good idea for conda to be  able to --dry-run and solve and environment for another platform than the one it's on. So you could do `conda create -f env.yaml --dry-run=win` and see error messages if packages can't get installed.
